/**
 * responsiveVariants.ts
 *
 * Uses Vite's `import.meta.glob` to eagerly import all responsive WebP
 * variants generated by scripts/generate-responsive-images.mjs and
 * exports a lookup function mapping an original image path to its variants.
 */

// All responsive variants live in src/assets-responsive/
// The glob returns paths relative to THIS file, e.g. "../assets-responsive/hero-img/AboutHero-400.webp"
const variantModules = import.meta.glob<{
  default: string;
}>("../assets-responsive/**/*.webp", { eager: true });

// Build a map:  "hero-img/AboutHero" → { 400: url, 800: url, 1200: url }
const WIDTHS = [400, 800, 1200, 1600] as const;

type ResponsiveSet = Partial<Record<(typeof WIDTHS)[number], string>>;

const variantMap = new Map<string, ResponsiveSet>();

for (const [globPath, mod] of Object.entries(variantModules)) {
  // Extract folder + base name from the glob path:
  // "../../assets-responsive/hero-img/AboutHero-400.webp"
  //  → folder: "hero-img", name: "AboutHero", width: 400
  const parts = globPath.split("/");
  const fileName = parts[parts.length - 1]; // "AboutHero-400.webp"
  const folder = parts[parts.length - 2]; // "hero-img"
  const match = fileName.match(/^(.+)-(\d+)\.webp$/);
  if (!match) continue;

  const [, baseName, widthStr] = match;
  const width = Number(widthStr) as (typeof WIDTHS)[number];
  const key = `${folder}/${baseName}`;

  if (!variantMap.has(key)) {
    variantMap.set(key, {} as ResponsiveSet);
  }
  variantMap.get(key)![width] = mod.default;
}

/**
 * Given an original Vite-imported image URL, return responsive WebP variant URLs.
 *
 * Vite hashes URLs like: /assets/AboutHero-abc123.png
 * We extract the original folder/name to look up variants.
 *
 * Returns null if no responsive variants exist (small images are skipped).
 */
export function getResponsiveVariants(
  originalSrc: string
): ResponsiveSet | null {
  // Vite-imported URLs look like:
  //   "/assets/hero-img/AboutHero-DxYz123.png"  (publicPath mode)
  //   "/src/assets/hero-img/AboutHero.png"      (dev mode)
  //   "https://cdn.../AboutHero-DxYz123.png"    (unlikely but handle)

  // Try to extract folder/filename patterns
  for (const [key, variants] of variantMap) {
    // key = "hero-img/AboutHero"
    const fileName = key.split("/")[1]; // "AboutHero"
    if (originalSrc.includes(fileName)) {
      return variants;
    }
  }

  return null;
}

export { WIDTHS };
export type { ResponsiveSet };
