/**
 * responsiveVariants.ts
 *
 * Picks up the responsive WebP variants generated by
 * scripts/generate-responsive-images.mjs (run `npm run images:responsive`)
 * and exports a lookup that maps an original image URL to its variants.
 */

// All variants live in src/assets-responsive/, mirroring src/assets/ layout.
// Glob paths are relative to THIS file, e.g. "../assets-responsive/hero-img/AboutHero-400.webp"
const variantModules = import.meta.glob<{ default: string }>(
  "../assets-responsive/**/*.webp",
  { eager: true },
);

export const WIDTHS = [400, 800, 1200, 1600] as const;

export type ResponsiveSet = Partial<Record<(typeof WIDTHS)[number], string>>;

type VariantKey = string; // base name, e.g. "AboutHero" — unique across src/assets (verified)

// base name → { 400: url, 800: url, ... }
const variantMap = new Map<VariantKey, ResponsiveSet>();

for (const [globPath, mod] of Object.entries(variantModules)) {
  const fileName = globPath.split("/").pop() ?? ""; // "AboutHero-400.webp"
  const match = fileName.match(/^(.+)-(\d+)\.webp$/);
  if (!match) continue;

  const width = Number(match[2]) as (typeof WIDTHS)[number];
  const set = variantMap.get(match[1]) ?? {};
  set[width] = mod.default;
  variantMap.set(match[1], set);
}

/**
 * Given an original Vite-imported image URL, return its responsive WebP
 * variants, or null when none exist (plain <img> is the right fallback then).
 *
 * Matches on base file name only: Vite flattens asset URLs in production
 * ("/assets/AboutHero-DxYz.webp"), so folder info isn't reliably present.
 * Base names are unique across src/assets, so this is unambiguous.
 */
export function getResponsiveVariants(originalSrc: string): ResponsiveSet | null {
  const fileName = originalSrc.split("/").pop() ?? "";
  const stem = fileName.replace(/\.(?:png|jpe?g|webp)(?:[?#].*)?$/i, "");
  // In production Vite appends an 8-char hash ("AboutHero-DxYz1234"); in dev
  // there is no hash ("athletics-training"). A name segment can itself look
  // hash-like ("-training"), so try the hash-stripped name first, then the raw stem.
  const candidates = /-[A-Za-z0-9_-]{8}$/.test(stem)
    ? [stem.replace(/-[A-Za-z0-9_-]{8}$/, ""), stem]
    : [stem];
  for (const candidate of candidates) {
    const set = variantMap.get(candidate);
    if (set) return set;
  }
  return null;
}
