import {
  Apple,ArrowLeftRight,Banknote,BarChart3,Briefcase,Building2,Candy,Car,ClipboardList,Clock,CreditCard,Crown,Dumbbell,Factory,FlaskConical,
  Globe,GraduationCap,HandCoins,HeartPulse,Home,Image,KeyRound,Landmark,Layers,Leaf,Lock,MapPin,MapPinned,Medal,PenTool,Route,SearchCheck,
  ShieldCheck,Ship,Snowflake,Sprout,Store,Swords,Ticket,TrendingUp,Trophy,Truck,Users,Wallet,Warehouse,Wheat,
} from "lucide-react";

export const serviceIcons: Record<string, React.ComponentType<{ size?: number; strokeWidth?: number; className?: string }>> = {
  "Investor Services": Users,
  "FDI Advisory & Facilitation": MapPinned,
  "NBFC Operations": Landmark,
  "Banking & Institutional Funding": HandCoins,
  "Cross-Border Capital Solutions": Globe,
  "Wealth & Asset Advisory": TrendingUp,

  "Personal Loan": Wallet,
  "Business Loan": Building2,
  "Home Loan": Home,
  "Loan Against Property": KeyRound,
  "Balance Transfer": ArrowLeftRight,
  "Car Loan": Car,
  "Credit Card": CreditCard,
  "Education Loan": GraduationCap,
  "Project Loan": Briefcase,
  "Commercial Purchase": Store,
  "Lease R Discounting": HandCoins,
  "Working Capital": Banknote,

  "Armed Security Guards": ShieldCheck,
  "Commando Protection Units": Swords,
  "VIP & Dignitary Escorts": Crown,
  "Event & Venue Security": Ticket,
  "Corporate & Site Security": Factory,
  "24×7 Monitoring & Rapid Response": Clock,

  "Sugar Export & Trading": Candy,
  "Edible Oils & Pulses": Leaf,
  "Food Grains & Spices": Wheat,
  "Sourcing & Quality Control": SearchCheck,
  "International Logistics": Ship,
  "14 South American Markets": Globe,

  "Organic Fertilizer Production": Sprout,
  "Bio-Fertilizer Blends": Leaf,
  "Soil Health Solutions": FlaskConical,
  "Yield Improvement Programmes": TrendingUp,
  "Farmer Support & Training": Users,
  "Shamli, UP Facility (Delhi NCR)": MapPin,

  "Warehousing on Lease (MNCs)": Warehouse,
  "Secure & Scalable Storage": Lock,
  "Inventory Management": ClipboardList,
  "Delhi NCR Locations": MapPin,
  "Logistics Integration": Truck,
  "Cold & Dry Storage Options": Snowflake,

  "Highway Hoardings & Billboards": Image,
  "Multiple Site Holdings": Layers,
  "High-Traffic Corridor Placements": Route,
  "Creative & Campaign Support": PenTool,
  "Site Analytics & Reporting": BarChart3,

  "International-Level Training": Dumbbell,
  "Diet & Nutrition Programmes": Apple,
  "Expert Coaching & Mentorship": Users,
  "Competition Funding & Gear": Medal,
  "Sports Medicine & Recovery": HeartPulse,
  "Olympic-Grade Support": Trophy,
};
