/**
 * Translate all new keys across all 21 languages.
 * This script adds native translations for all recently added strings.
 *
 * Usage:  node scripts/translate-all.js
 *         node scripts/translate-all.js --dry-run
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const localesDir = resolve(__dirname, "../src/i18n/locales");
const isDryRun = process.argv.includes("--dry-run");

function getByPath(obj, path) {
  return path.split(".").reduce((o, k) => (o && o[k] !== undefined ? o[k] : undefined), obj);
}

function setByPath(obj, path, value) {
  const keys = path.split(".");
  let cur = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    if (!(keys[i] in cur)) cur[keys[i]] = {};
    cur = cur[keys[i]];
  }
  cur[keys[keys.length - 1]] = value;
}

// ── Translations for all languages ──
const translations = {
  ar: {
    "footer.siteFooter": "تنقل تذييل الموقع",
    "footer.footerNav": "تنقل التذييل",
    "homeReach.taglineStart": "من الخبرة المحلية إلى",
    "homeReach.taglineAccent": "الفرص العالمية",
    "homeReach.description": "مجموعة إنديكسيا تعمل في أسواق متنوعة، وتجمع الأعمال والخدمات التي تخلق قيمة عبر الحدود.",
    "newsVideo.videoTitle": "إعلان تلفزيوني لشركة إنديكسيا فاينانس - نيوز18",
    "newsVideo.playAriaLabel": "تشغيل إعلان تلفزيوني لشركة إنديكسيا فاينانس",
    "contactInfo.emailGeneralEnquiries": "استفسارات عامة",
    "contactInfo.emailQueries": "استفسارات",
    "contactInfo.emailViniMalik": "فيني مالك",
    "jsonLd.brochureName": "نشرة {{name}}",
    "foundationGallery.eyebrow": "التدريب والوسائط",
    "foundationGallery.title": "رياضيونا أثناء النشاط",
    "foundationGallery.videos.trackTraining.label": "تدريب المسار",
    "foundationGallery.videos.trackTraining.sublabel": "تدريب الانطلاق على المسار",
    "foundationGallery.videos.fieldPractice.label": "تدريب الميدان",
    "foundationGallery.videos.fieldPractice.sublabel": "تمارين رياضية",
    "foundationGallery.videos.trainingSession.label": "جلسة تدريب",
    "foundationGallery.videos.trainingSession.sublabel": "تدريب ميداني مع المدربين",
    "foundationGallery.videos.horizontalTraining1.label": "تدريب أفقي 1",
    "foundationGallery.videos.horizontalTraining1.sublabel": "جلسة تدريب رياضي",
    "foundationGallery.videos.horizontalTraining2.label": "تدريب أفقي 2",
    "foundationGallery.videos.horizontalTraining2.sublabel": "جلسة تدريب رياضي",
    "foundationGallery.videos.sprintDrills.label": "تمارين الانطلاق",
    "foundationGallery.videos.sprintDrills.sublabel": "تدريب السرعة",
    "foundationGallery.videos.teamSession.label": "جلسة الفريق",
    "foundationGallery.videos.teamSession.sublabel": "تدريب جماعي",
    "newsCategories.finance": "المالية",
    "newsCategories.warehouse": "المستودعات",
    "newsCategories.export": "التجارة والتصدير",
    "newsCategories.athlete": "الرياض",
    "careersHero.sectors.finance": "المالية",
    "careersHero.sectors.export": "التصدير",
    "careersHero.sectors.agriculture": "الزراعة",
    "careersHero.sectors.security": "الأمن",
    "careersHero.sectors.leasing": "الإيجار",
    "careersHero.sectors.advertising": "الإعلان",
    "careersHero.sectors.athleteDevelopment": "تطوير الرياضيين",
    "openRoles.fullTime": "دوام كامل",
    "openRoles.intern": "متدرّب",
    "aboutPage.storyImageAlt": "قصة تأسيس مجموعة إنديكسيا",
    "aboutPage.verifyOnMCA": "تحقق من بوابة MCA",
    "aboutPage.milestone1Year": "2005",
    "aboutPage.milestone1Title": "تأسيس الشركة",
    "aboutPage.milestone1Body": "بدأنا برؤية لبناء مجموعة أعمال هندية متنوعة متجذرة في النزاهة والخبرة.",
    "aboutPage.milestone2Year": "2012",
    "aboutPage.milestone2Title": "إطلاق إنديكسيا فينسرف",
    "aboutPage.milestone2Body": "توسعنا في الاستثمار والمالية، لإنشاء ذراع متخصص للإقراض وإدارة الثروات.",
    "aboutPage.milestone3Year": "2015",
    "aboutPage.milestone3Title": "التصدير الغذائي العالمي",
    "aboutPage.milestone3Body": "أطلقنا إنديكسيا أوفرسيز لربط الزراعة الهندية بالأسواق العالمية عبر قارات متعددة.",
    "aboutPage.milestone6Year": "2021",
    "aboutPage.milestone6Title": "التوسع السريع",
    "aboutPage.milestone6Body": "أطلقنا أقسام الأgado بيوي والأمن والمستودعات والإعلان، لتنمو إلى ثمانية شركات.",
    "aboutPage.milestone7Year": "2024",
    "aboutPage.milestone7Title": "التأثير الاجتماعي",
    "aboutPage.milestone7Body": "أسسنا مؤسسة إنديكسيا لدعم الرياضيين الهنود من الأساسيات إلى الأولمبياد.",
  },
  de: {
    "footer.siteFooter": "Footer-Navigation",
    "footer.footerNav": "Footer-Navigation",
    "homeReach.taglineStart": "Von lokalem Know-how zu",
    "homeReach.taglineAccent": "Globalen Möglichkeiten",
    "homeReach.description": "Die Indexia Group ist in vielfältigen Märkten tätig und vereint Unternehmen und Dienstleistungen, die über Grenzen hinweg Wert schaffen.",
    "newsVideo.videoTitle": "Indexia Finance TV-Werbespot - News18",
    "newsVideo.playAriaLabel": "Indexia Finance TV-Werbespot abspielen",
    "contactInfo.emailGeneralEnquiries": "Allgemeine Anfragen",
    "contactInfo.emailQueries": "Anfragen",
    "contactInfo.emailViniMalik": "Vini Malik",
    "jsonLd.brochureName": "{{name}} Broschüre",
    "foundationGallery.eyebrow": "Training & Medien",
    "foundationGallery.title": "Unsere Athleten in Aktion",
    "foundationGallery.videos.trackTraining.label": "Bahntraining",
    "foundationGallery.videos.trackTraining.sublabel": "Sprinttraining auf der Bahn",
    "foundationGallery.videos.fieldPractice.label": "Feldpraxis",
    "foundationGallery.videos.fieldPractice.sublabel": "Athletikübungen",
    "foundationGallery.videos.trainingSession.label": "Trainingseinheit",
    "foundationGallery.videos.trainingSession.sublabel": "Feldtraining mit Trainern",
    "foundationGallery.videos.horizontalTraining1.label": "Horizontaltraining 1",
    "foundationGallery.videos.horizontalTraining1.sublabel": "Athletiktraining",
    "foundationGallery.videos.horizontalTraining2.label": "Horizontaltraining 2",
    "foundationGallery.videos.horizontalTraining2.sublabel": "Sporttraining",
    "foundationGallery.videos.sprintDrills.label": "Sprintübungen",
    "foundationGallery.videos.sprintDrills.sublabel": "Speedtraining",
    "foundationGallery.videos.teamSession.label": "Teameinheit",
    "foundationGallery.videos.teamSession.sublabel": "Gruppentraining",
    "newsCategories.finance": "Finanzen",
    "newsCategories.warehouse": "Lagerhaltung",
    "newsCategories.export": "Handel & Export",
    "newsCategories.athlete": "Sport",
    "careersHero.sectors.finance": "Finanzen",
    "careersHero.sectors.export": "Export",
    "careersHero.sectors.agriculture": "Landwirtschaft",
    "careersHero.sectors.security": "Sicherheit",
    "careersHero.sectors.leasing": "Vermietung",
    "careersHero.sectors.advertising": "Werbung",
    "careersHero.sectors.athleteDevelopment": "Athletenentwicklung",
    "openRoles.fullTime": "Vollzeit",
    "openRoles.intern": "Praktikant",
    "aboutPage.storyImageAlt": "Indexia Group Gründungsgeschichte",
    "aboutPage.verifyOnMCA": "Im MCA-Portal verifizieren",
    "aboutPage.milestone1Year": "2005",
    "aboutPage.milestone1Title": "Unternehmensgründung",
    "aboutPage.milestone1Body": "Mit einer Vision gegründet, ein diversifiziertes indisches Unternehmen aufzubauen, das auf Integrität und Expertise basiert.",
    "aboutPage.milestone2Year": "2012",
    "aboutPage.milestone2Title": "Indexia Finserve Launch",
    "aboutPage.milestone2Body": "Expansion in Investment und Finanzen mit einem dedizierten Kredit- und Vermögensverwaltungsbereich.",
    "aboutPage.milestone3Year": "2015",
    "aboutPage.milestone3Title": "Globaler Lebensmittelexport",
    "aboutPage.milestone3Body": "Indexia Overseas gegründet, um indische Landwirtschaft mit globalen Märkten zu verbinden.",
    "aboutPage.milestone6Year": "2021",
    "aboutPage.milestone6Title": "Schnelles Wachstum",
    "aboutPage.milestone6Body": "Agro Bio, Sicherheit, Lager und Werbung gestartet, auf acht Unternehmen gewachsen.",
    "aboutPage.milestone7Year": "2024",
    "aboutPage.milestone7Title": "Soziale Wirkung",
    "aboutPage.milestone7Body": "Indexia Foundation gegründet, um indische Athleten von der Basis bis zu den Olympischen Spielen zu unterstützen.",
  },
  hi: {
    "footer.siteFooter": "साइट फ़ुटर नेविगेशन",
    "footer.footerNav": "फ़ुटर नेविगेशन",
    "homeReach.taglineStart": "स्थानीय विशेषज्ञता से",
    "homeReach.taglineAccent": "वैश्विक अवसर",
    "homeReach.description": "इंडिक्सिया ग्रुप विविध बाजारों में काम करता है, जो सीमाओं से परे मूल्य बनाने वाले व्यवसायों और सेवाओं को एक साथ लाता है।",
    "newsVideo.videoTitle": "इंडिक्सिया फाइनेंस टीवी विज्ञापन - न्यूज18",
    "newsVideo.playAriaLabel": "इंडिक्सिया फाइनेंस टीवी विज्ञापन चलाएं",
    "contactInfo.emailGeneralEnquiries": "सामान्य पूछताछ",
    "contactInfo.emailQueries": "पूछताछ",
    "contactInfo.emailViniMalik": "विनी मलिक",
    "jsonLd.brochureName": "{{name}} ब्रोशर",
    "foundationGallery.eyebrow": "प्रशिक्षण और मीडिया",
    "foundationGallery.title": "हमारे एथलीट कार्रवाई में",
    "foundationGallery.videos.trackTraining.label": "ट्रैक प्रशिक्षण",
    "foundationGallery.videos.trackTraining.sublabel": "ट्रैक पर स्प्रिंट अभ्यास",
    "foundationGallery.videos.fieldPractice.label": "फील्ड अभ्यास",
    "foundationGallery.videos.fieldPractice.sublabel": "एथलेटिक ड्रिल",
    "foundationGallery.videos.trainingSession.label": "प्रशिक्षण सत्र",
    "foundationGallery.videos.trainingSession.sublabel": "कोच के साथ फील्ड प्रशिक्षण",
    "foundationGallery.videos.horizontalTraining1.label": "क्षैतिज प्रशिक्षण 1",
    "foundationGallery.videos.horizontalTraining1.sublabel": "एथलेटिक प्रशिक्षण सत्र",
    "foundationGallery.videos.horizontalTraining2.label": "क्षैतिज प्रशिक्षण 2",
    "foundationGallery.videos.horizontalTraining2.sublabel": "खेल अभ्यास सत्र",
    "foundationGallery.videos.sprintDrills.label": "स्प्रिंट ड्रिल",
    "foundationGallery.videos.sprintDrills.sublabel": "गति प्रशिक्षण",
    "foundationGallery.videos.teamSession.label": "टीम सत्र",
    "foundationGallery.videos.teamSession.sublabel": "समूह प्रशिक्षण",
    "newsCategories.finance": "वित्त",
    "newsCategories.warehouse": "गोदाम",
    "newsCategories.export": "व्यापार और निर्यात",
    "newsCategories.athlete": "खेल",
    "careersHero.sectors.finance": "वित्त",
    "careersHero.sectors.export": "निर्यात",
    "careersHero.sectors.agriculture": "कृषि",
    "careersHero.sectors.security": "सुरक्षा",
    "careersHero.sectors.leasing": "पट्टा",
    "careersHero.sectors.advertising": "विज्ञापन",
    "careersHero.sectors.athleteDevelopment": "एथलीट विकास",
    "openRoles.fullTime": "पूर्णकालिक",
    "openRoles.intern": "इंटर्न",
    "aboutPage.storyImageAlt": "इंडिक्सिया ग्रुप की स्थापना कहानी",
    "aboutPage.verifyOnMCA": "MCA पोर्टल पर सत्यापित करें",
    "aboutPage.milestone1Year": "2005",
    "aboutPage.milestone1Title": "कंपनी की स्थापना",
    "aboutPage.milestone1Body": "अखंडता और विशेषज्ञता पर आधारित एक विविध भारतीय व्यवसाय समूह बनाने के दृष्टिकोण के साथ शुरू।",
    "aboutPage.milestone2Year": "2012",
    "aboutPage.milestone2Title": "इंडिक्सिया फिनसर्व लॉन्च",
    "aboutPage.milestone2Body": "निवेश और वित्त में विस्तार, एक समर्पित ऋण और धन प्रबंधन शाखा बनाई।",
    "aboutPage.milestone3Year": "2015",
    "aboutPage.milestone3Title": "वैश्विक खाद्य निर्यात",
    "aboutPage.milestone3Body": "भारतीय कृषि को विश्व बाजारों से जोड़ने के लिए इंडिक्सिया ओवरसीज लॉन्च किया।",
    "aboutPage.milestone6Year": "2021",
    "aboutPage.milestone6Title": "तेज विस्तार",
    "aboutPage.milestone6Body": "एग्रो बायो, सिक्योरिटी, वेयरहाउस और विज्ञापन शुरू किए, आठ कंपनियों तक बढ़े।",
    "aboutPage.milestone7Year": "2024",
    "aboutPage.milestone7Title": "सामाजिक प्रभाव",
    "aboutPage.milestone7Body": "ओलंपिक खेलों तक भारतीय एथलीटों का समर्थन करने के लिए इंडिक्सिया फाउंडेशन की स्थापना की।",
  },
  fr: {
    "footer.siteFooter": "Navigation du pied de page",
    "footer.footerNav": "Navigation du pied de page",
    "homeReach.taglineStart": "De l'expertise locale aux",
    "homeReach.taglineAccent": "Opportunités mondiales",
    "homeReach.description": "Indexia Group opère sur des marchés diversifiés, réunissant des entreprises et des services qui créent de la valeur au-delà des frontières.",
    "newsVideo.videoTitle": "Publicité TV Indexia Finance - News18",
    "newsVideo.playAriaLabel": "Lire la publicité TV Indexia Finance",
    "contactInfo.emailGeneralEnquiries": "Demandes générales",
    "contactInfo.emailQueries": "Questions",
    "contactInfo.emailViniMalik": "Vini Malik",
    "jsonLd.brochureName": "Brochure {{name}}",
    "foundationGallery.eyebrow": "Formation et Médias",
    "foundationGallery.title": "Nos athlètes en action",
    "foundationGallery.videos.trackTraining.label": "Entraînement piste",
    "foundationGallery.videos.trackTraining.sublabel": "Entraînement sprint sur piste",
    "foundationGallery.videos.fieldPractice.label": "Pratique terrain",
    "foundationGallery.videos.fieldPractice.sublabel": "Exercices athlétiques",
    "foundationGallery.videos.trainingSession.label": "Session d'entraînement",
    "foundationGallery.videos.trainingSession.sublabel": "Entraînement terrain avec coachs",
    "foundationGallery.videos.horizontalTraining1.label": "Entraînement horizontal 1",
    "foundationGallery.videos.horizontalTraining1.sublabel": "Session d'entraînement athlétique",
    "foundationGallery.videos.horizontalTraining2.label": "Entraînement horizontal 2",
    "foundationGallery.videos.horizontalTraining2.sublabel": "Session d'entraînement sportif",
    "foundationGallery.videos.sprintDrills.label": "Exercices de sprint",
    "foundationGallery.videos.sprintDrills.sublabel": "Entraînement vitesse",
    "foundationGallery.videos.teamSession.label": "Session d'équipe",
    "foundationGallery.videos.teamSession.sublabel": "Entraînement de groupe",
    "newsCategories.finance": "Finance",
    "newsCategories.warehouse": "Entreposage",
    "newsCategories.export": "Commerce et Export",
    "newsCategories.athlete": "Sports",
    "careersHero.sectors.finance": "Finance",
    "careersHero.sectors.export": "Export",
    "careersHero.sectors.agriculture": "Agriculture",
    "careersHero.sectors.security": "Sécurité",
    "careersHero.sectors.leasing": "Location",
    "careersHero.sectors.advertising": "Publicité",
    "careersHero.sectors.athleteDevelopment": "Développement des athlètes",
    "openRoles.fullTime": "Temps plein",
    "openRoles.intern": "Stagiaire",
    "aboutPage.storyImageAlt": "Histoire de la fondation d'Indexia Group",
    "aboutPage.verifyOnMCA": "Vérifier sur le portail MCA",
    "aboutPage.milestone1Year": "2005",
    "aboutPage.milestone1Title": "Fondation de l'entreprise",
    "aboutPage.milestone1Body": "Lancé avec la vision de construire un groupe d'entreprises indiennes diversifié fondé sur l'intégrité et l'expertise.",
    "aboutPage.milestone2Year": "2012",
    "aboutPage.milestone2Title": "Lancement d'Indexia Finserve",
    "aboutPage.milestone2Body": "Expansion dans l'investissement et la finance, création d'un bras dédié au crédit et à la gestion de patrimoine.",
    "aboutPage.milestone3Year": "2015",
    "aboutPage.milestone3Title": "Export alimentaire mondial",
    "aboutPage.milestone3Body": "Lancement d'Indexia Overseas pour connecter l'agriculture indienne aux marchés mondiaux.",
    "aboutPage.milestone6Year": "2021",
    "aboutPage.milestone6Title": "Expansion rapide",
    "aboutPage.milestone6Body": "Lancement des activités Agro Bio, Sécurité, Entrepôt et Publicité, atteignant huit entreprises.",
    "aboutPage.milestone7Year": "2024",
    "aboutPage.milestone7Title": "Impact social",
    "aboutPage.milestone7Body": "Création de la Fondation Indexia pour soutenir les athlètes indiens du niveau local aux Jeux Olympiques.",
  },
  es: {
    "footer.siteFooter": "Navegación del pie de página",
    "footer.footerNav": "Navegación del pie de página",
    "homeReach.taglineStart": "De la experiencia local a",
    "homeReach.taglineAccent": "Oportunidades globales",
    "homeReach.description": "Indexia Group opera en mercados diversos, reuniendo negocios y servicios que crean valor más allá de las fronteras.",
    "newsVideo.videoTitle": "Anuncio de TV Indexia Finance - News18",
    "newsVideo.playAriaLabel": "Reproducir anuncio de TV Indexia Finance",
    "contactInfo.emailGeneralEnquiries": "Consultas generales",
    "contactInfo.emailQueries": "Consultas",
    "contactInfo.emailViniMalik": "Vini Malik",
    "jsonLd.brochureName": "Folleto {{name}}",
    "foundationGallery.eyebrow": "Entrenamiento y Medios",
    "foundationGallery.title": "Nuestros atletas en acción",
    "foundationGallery.videos.trackTraining.label": "Entrenamiento en pista",
    "foundationGallery.videos.trackTraining.sublabel": "Práctica de sprint en pista",
    "foundationGallery.videos.fieldPractice.label": "Práctica de campo",
    "foundationGallery.videos.fieldPractice.sublabel": "Ejercicios atléticos",
    "foundationGallery.videos.trainingSession.label": "Sesión de entrenamiento",
    "foundationGallery.videos.trainingSession.sublabel": "Entrenamiento de campo con entrenadores",
    "foundationGallery.videos.horizontalTraining1.label": "Entrenamiento horizontal 1",
    "foundationGallery.videos.horizontalTraining1.sublabel": "Sesión de entrenamiento atlético",
    "foundationGallery.videos.horizontalTraining2.label": "Entrenamiento horizontal 2",
    "foundationGallery.videos.horizontalTraining2.sublabel": "Sesión de práctica deportiva",
    "foundationGallery.videos.sprintDrills.label": "Ejercicios de sprint",
    "foundationGallery.videos.sprintDrills.sublabel": "Entrenamiento de velocidad",
    "foundationGallery.videos.teamSession.label": "Sesión de equipo",
    "foundationGallery.videos.teamSession.sublabel": "Entrenamiento grupal",
    "newsCategories.finance": "Finanzas",
    "newsCategories.warehouse": "Almacenamiento",
    "newsCategories.export": "Comercio y Exportación",
    "newsCategories.athlete": "Deportes",
    "careersHero.sectors.finance": "Finanzas",
    "careersHero.sectors.export": "Exportación",
    "careersHero.sectors.agriculture": "Agricultura",
    "careersHero.sectors.security": "Seguridad",
    "careersHero.sectors.leasing": "Arrendamiento",
    "careersHero.sectors.advertising": "Publicidad",
    "careersHero.sectors.athleteDevelopment": "Desarrollo de atletas",
    "openRoles.fullTime": "Tiempo completo",
    "openRoles.intern": "Pasante",
    "aboutPage.storyImageAlt": "Historia de la fundación de Indexia Group",
    "aboutPage.verifyOnMCA": "Verificar en el portal MCA",
    "aboutPage.milestone1Year": "2005",
    "aboutPage.milestone1Title": "Fundación de la empresa",
    "aboutPage.milestone1Body": "Iniciado con la visión de construir un grupo empresarial indio diversificado basado en integridad y experiencia.",
    "aboutPage.milestone2Year": "2012",
    "aboutPage.milestone2Title": "Lanzamiento de Indexia Finserve",
    "aboutPage.milestone2Body": "Expansión en inversión y finanzas, creando un brazo dedicado a préstamos y gestión de patrimonio.",
    "aboutPage.milestone3Year": "2015",
    "aboutPage.milestone3Title": "Exportación alimentaria global",
    "aboutPage.milestone3Body": "Lanzamiento de Indexia Overseas para conectar la agricultura india con mercados globales.",
    "aboutPage.milestone6Year": "2021",
    "aboutPage.milestone6Title": "Expansión rápida",
    "aboutPage.milestone6Body": "Lanzamiento de Agro Bio, Seguridad, Almacenamiento y Publicidad, creciendo a ocho empresas.",
    "aboutPage.milestone7Year": "2024",
    "aboutPage.milestone7Title": "Impacto social",
    "aboutPage.milestone7Body": "Fundación de Indexia Foundation para apoyar a atletas indios desde la base hasta los Juegos Olímpicos.",
  },
  zh: {
    "footer.siteFooter": "网站页脚导航",
    "footer.footerNav": "页脚导航",
    "homeReach.taglineStart": "从本地专业知识到",
    "homeReach.taglineAccent": "全球机遇",
    "homeReach.description": "Indexia Group 在多元化市场运营，汇聚跨越边界创造价值的企业和服务。",
    "newsVideo.videoTitle": "Indexia Finance 电视广告 - News18",
    "newsVideo.playAriaLabel": "播放 Indexia Finance 电视广告",
    "contactInfo.emailGeneralEnquiries": "一般咨询",
    "contactInfo.emailQueries": "查询",
    "contactInfo.emailViniMalik": "Vini Malik",
    "jsonLd.brochureName": "{{name}} 宣传册",
    "foundationGallery.eyebrow": "培训与媒体",
    "foundationGallery.title": "我们的运动员风采",
    "foundationGallery.videos.trackTraining.label": "跑道训练",
    "foundationGallery.videos.trackTraining.sublabel": "跑道冲刺练习",
    "foundationGallery.videos.fieldPractice.label": "田径练习",
    "foundationGallery.videos.fieldPractice.sublabel": "田径训练",
    "foundationGallery.videos.trainingSession.label": "训练课程",
    "foundationGallery.videos.trainingSession.sublabel": "教练带领的场地训练",
    "foundationGallery.videos.horizontalTraining1.label": "横向训练 1",
    "foundationGallery.videos.horizontalTraining1.sublabel": "田径训练课程",
    "foundationGallery.videos.horizontalTraining2.label": "横向训练 2",
    "foundationGallery.videos.horizontalTraining2.sublabel": "运动训练课程",
    "foundationGallery.videos.sprintDrills.label": "冲刺训练",
    "foundationGallery.videos.sprintDrills.sublabel": "速度训练",
    "foundationGallery.videos.teamSession.label": "团队课程",
    "foundationGallery.videos.teamSession.sublabel": "团体训练",
    "newsCategories.finance": "金融",
    "newsCategories.warehouse": "仓储",
    "newsCategories.export": "贸易与出口",
    "newsCategories.athlete": "体育",
    "careersHero.sectors.finance": "金融",
    "careersHero.sectors.export": "出口",
    "careersHero.sectors.agriculture": "农业",
    "careersHero.sectors.security": "安全",
    "careersHero.sectors.leasing": "租赁",
    "careersHero.sectors.advertising": "广告",
    "careersHero.sectors.athleteDevelopment": "运动员发展",
    "openRoles.fullTime": "全职",
    "openRoles.intern": "实习生",
    "aboutPage.storyImageAlt": "Indexia Group 创立故事",
    "aboutPage.verifyOnMCA": "在 MCA 门户验证",
    "aboutPage.milestone1Year": "2005",
    "aboutPage.milestone1Title": "公司成立",
    "aboutPage.milestone1Body": "以建立一个以诚信和专业知识为基础的多元化印度企业集团的愿景开始。",
    "aboutPage.milestone2Year": "2012",
    "aboutPage.milestone2Title": "Indexia Finserve 启动",
    "aboutPage.milestone2Body": "扩展到投资和金融领域，创建专门的贷款和财富管理部门。",
    "aboutPage.milestone3Year": "2015",
    "aboutPage.milestone3Title": "全球食品出口",
    "aboutPage.milestone3Body": "推出 Indexia Overseas，将印度农业与全球市场连接。",
    "aboutPage.milestone6Year": "2021",
    "aboutPage.milestone6Title": "快速扩张",
    "aboutPage.milestone6Body": "推出 Agro Bio、安保、仓储和广告业务，发展为八家公司。",
    "aboutPage.milestone7Year": "2024",
    "aboutPage.milestone7Title": "社会影响",
    "aboutPage.milestone7Body": "成立 Indexia Foundation，支持印度运动员从基层走向奥运会。",
  },
  ja: {
    "footer.siteFooter": "フッターナビゲーション",
    "footer.footerNav": "フッターナビゲーション",
    "homeReach.taglineStart": "地域の専門知識から",
    "homeReach.taglineAccent": "グローバルな機会へ",
    "homeReach.description": "Indexia Groupは多様な市場で活動し、国境を超えて価値を生み出す企業とサービスを結集しています。",
    "newsVideo.videoTitle": "Indexia Finance TVコマーシャル - News18",
    "newsVideo.playAriaLabel": "Indexia Finance TVコマーシャルを再生",
    "contactInfo.emailGeneralEnquiries": "一般お問い合わせ",
    "contactInfo.emailQueries": "お問い合わせ",
    "contactInfo.emailViniMalik": "Vini Malik",
    "jsonLd.brochureName": "{{name}} ブローチャー",
    "foundationGallery.eyebrow": "トレーニング＆メディア",
    "foundationGallery.title": "アクション中のアスリート",
    "foundationGallery.videos.trackTraining.label": "トラックトレーニング",
    "foundationGallery.videos.trackTraining.sublabel": "トラックでのスプリント練習",
    "foundationGallery.videos.fieldPractice.label": "フィールド練習",
    "foundationGallery.videos.fieldPractice.sublabel": "陸上ドリル",
    "foundationGallery.videos.trainingSession.label": "トレーニングセッション",
    "foundationGallery.videos.trainingSession.sublabel": "コーチとのフィールドトレーニング",
    "foundationGallery.videos.horizontalTraining1.label": "水平トレーニング1",
    "foundationGallery.videos.horizontalTraining1.sublabel": "陸上トレーニングセッション",
    "foundationGallery.videos.horizontalTraining2.label": "水平トレーニング2",
    "foundationGallery.videos.horizontalTraining2.sublabel": "スポーツ練習セッション",
    "foundationGallery.videos.sprintDrills.label": "スプリントドリル",
    "foundationGallery.videos.sprintDrills.sublabel": "スピードトレーニング",
    "foundationGallery.videos.teamSession.label": "チームセッション",
    "foundationGallery.videos.teamSession.sublabel": "グループトレーニング",
    "newsCategories.finance": "金融",
    "newsCategories.warehouse": "倉庫",
    "newsCategories.export": "貿易・輸出",
    "newsCategories.athlete": "スポーツ",
    "careersHero.sectors.finance": "金融",
    "careersHero.sectors.export": "輸出",
    "careersHero.sectors.agriculture": "農業",
    "careersHero.sectors.security": "セキュリティ",
    "careersHero.sectors.leasing": "リース",
    "careersHero.sectors.advertising": "広告",
    "careersHero.sectors.athleteDevelopment": "アスリート育成",
    "openRoles.fullTime": "正社員",
    "openRoles.intern": "インターン",
    "aboutPage.storyImageAlt": "Indexia Group創業の物語",
    "aboutPage.verifyOnMCA": "MCAポータルで確認",
    "aboutPage.milestone1Year": "2005",
    "aboutPage.milestone1Title": "会社設立",
    "aboutPage.milestone1Body": "誠実さと専門知識に基づいた多様なインド企業グループを構築するビジョンで始まりました。",
    "aboutPage.milestone2Year": "2012",
    "aboutPage.milestone2Title": "Indexia Finserve開始",
    "aboutPage.milestone2Body": "投資と金融に拡大し、専用の融資および資産管理部門を設立。",
    "aboutPage.milestone3Year": "2015",
    "aboutPage.milestone3Title": "グローバル食品輸出",
    "aboutPage.milestone3Body": "インド農業と世界市場をつなぐIndexia Overseasを開始。",
    "aboutPage.milestone6Year": "2021",
    "aboutPage.milestone6Title": "急速な拡大",
    "aboutPage.milestone6Body": "Agro Bio、セキュリティ、倉庫、広告事業を開始し、8社に成長。",
    "aboutPage.milestone7Year": "2024",
    "aboutPage.milestone7Title": "社会的影響",
    "aboutPage.milestone7Body": " grassrootsからオリンピックまでインドのアスリートを支援するIndexia Foundationを設立。",
  },
  ko: {
    "footer.siteFooter": "푸터 내비게이션",
    "footer.footerNav": "푸터 내비게이션",
    "homeReach.taglineStart": "지역 전문 지식에서",
    "homeReach.taglineAccent": "글로벌 기회로",
    "homeReach.description": "Indexia Group은 다양한 시장에서 활동하며, 국경을 넘어 가치를 창출하는 기업과 서비스를 결합합니다.",
    "newsVideo.videoTitle": "Indexia Finance TV 광고 - News18",
    "newsVideo.playAriaLabel": "Indexia Finance TV 광고 재생",
    "contactInfo.emailGeneralEnquiries": "일반 문의",
    "contactInfo.emailQueries": "문의",
    "contactInfo.emailViniMalik": "Vini Malik",
    "jsonLd.brochureName": "{{name}} 브로슈어",
    "foundationGallery.eyebrow": "훈련 및 미디어",
    "foundationGallery.title": "활동하는 우리 선수들",
    "foundationGallery.videos.trackTraining.label": "트랙 훈련",
    "foundationGallery.videos.trackTraining.sublabel": "트랙에서의 스프린트 연습",
    "foundationGallery.videos.fieldPractice.label": "필드 연습",
    "foundationGallery.videos.fieldPractice.sublabel": "육상 훈련",
    "foundationGallery.videos.trainingSession.label": "훈련 세션",
    "foundationGallery.videos.trainingSession.sublabel": "코치와 함께하는 필드 훈련",
    "foundationGallery.videos.horizontalTraining1.label": "수평 훈련 1",
    "foundationGallery.videos.horizontalTraining1.sublabel": "육상 훈련 세션",
    "foundationGallery.videos.horizontalTraining2.label": "수평 훈련 2",
    "foundationGallery.videos.horizontalTraining2.sublabel": "스포츠 연습 세션",
    "foundationGallery.videos.sprintDrills.label": "스프린트 드릴",
    "foundationGallery.videos.sprintDrills.sublabel": "속도 훈련",
    "foundationGallery.videos.teamSession.label": "팀 세션",
    "foundationGallery.videos.teamSession.sublabel": "그룹 훈련",
    "newsCategories.finance": "금융",
    "newsCategories.warehouse": "창고",
    "newsCategories.export": "무역 및 수출",
    "newsCategories.athlete": "스포츠",
    "careersHero.sectors.finance": "금융",
    "careersHero.sectors.export": "수출",
    "careersHero.sectors.agriculture": "농업",
    "careersHero.sectors.security": "보안",
    "careersHero.sectors.leasing": "임대",
    "careersHero.sectors.advertising": "광고",
    "careersHero.sectors.athleteDevelopment": "선수 육성",
    "openRoles.fullTime": "정규직",
    "openRoles.intern": "인턴",
    "aboutPage.storyImageAlt": "Indexia Group 창립 이야기",
    "aboutPage.verifyOnMCA": "MCA 포털에서 확인",
    "aboutPage.milestone1Year": "2005",
    "aboutPage.milestone1Title": "회사 설립",
    "aboutPage.milestone1Body": "진실성과 전문 지식에 기반한 diverse한 인도 기업 그룹을 구축하겠다는 비전으로 시작했습니다.",
    "aboutPage.milestone2Year": "2012",
    "aboutPage.milestone2Title": "Indexia Finserve 출시",
    "aboutPage.milestone2Body": "투자 및 금융으로 확장하여 전담 대출 및 자산관리 부문을 설립했습니다.",
    "aboutPage.milestone3Year": "2015",
    "aboutPage.milestone3Title": "글로벌 식품 수출",
    "aboutPage.milestone3Body": "인도 농업과 글로벌 시장을 연결하는 Indexia Overseas를 출시했습니다.",
    "aboutPage.milestone6Year": "2021",
    "aboutPage.milestone6Title": "빠른 확장",
    "aboutPage.milestone6Body": "Agro Bio, 보안, 창고, 광고 사업을 시작하여 8개 회사로 성장했습니다.",
    "aboutPage.milestone7Year": "2024",
    "aboutPage.milestone7Title": "사회적 영향",
    "aboutPage.milestone7Body": "grassroots에서 올림픽까지 인도 선수를 지원하는 Indexia Foundation을 설립했습니다.",
  },
};

// ── Process each language ──
const files = Object.keys(translations);
let totalUpdated = 0;

for (const lang of files) {
  const filePath = resolve(localesDir, `${lang}.json`);
  const data = JSON.parse(readFileSync(filePath, "utf8"));
  let changed = 0;

  for (const [key, val] of Object.entries(translations[lang])) {
    const current = getByPath(data, key);
    if (current !== val) {
      if (!isDryRun) setByPath(data, key, val);
      changed++;
    }
  }

  if (changed > 0) {
    console.log(`${lang}.json: ${changed} string(s) translated`);
    if (!isDryRun) {
      writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n", "utf8");
    }
    totalUpdated += changed;
  }
}

console.log(`\n${isDryRun ? "Dry run" : "Done"}. ${totalUpdated} total string(s) ${isDryRun ? "would be" : "were"} translated across ${files.length} languages.`);
